### ISSUE TITLE
Self Hosting

### ISSUE THREAD

**Issue by TecEash1** [coen-h/zmov#70]
Hi, when I try to self host this I am met with a blank screen even when I put in my TMDB API Key, also how would self hosting work, I see that no ``BASE_URL``s are filled in so how would the website work as intended?

**Comment by coen-h** [comment]
yo either make a seperate .env file to put the variables in, which i assume you did, or in my case i use vercels env variables to help hide them, reduce risk. if you did one of these i dont know why its still failing, try checking for console logs, might help. i can give you all the base_urls for the site, msg me on discord (herogg)
